export enum EventType {
  TICKET_CREATED = 'TICKET_CREATED',
  ASSIGNEE_ADDED = 'ASSIGNEE_ADDED',
  COMMENT_ADDED = 'COMMENT_ADDED',
  STATUS_CHANGED = 'STATUS_CHANGED',
  ATTACHMENT_ADDED = 'ATTACHMENT_ADDED'
}