import { MigrationInterface, QueryRunner } from "typeorm";

export class AddRetryTrackingToProcessedEvents1776171265832 implements MigrationInterface {
    name = 'AddRetryTrackingToProcessedEvents1776171265832'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "workspace_members" DROP CONSTRAINT "FK_workspace_members_user_id"`);
        await queryRunner.query(`ALTER TABLE "workspace_members" DROP CONSTRAINT "FK_workspace_members_workspace_id"`);
        await queryRunner.query(`ALTER TABLE "attachments" DROP CONSTRAINT "FK_attachments_uploaded_by"`);
        await queryRunner.query(`ALTER TABLE "attachments" DROP CONSTRAINT "FK_attachments_comment_id"`);
        await queryRunner.query(`ALTER TABLE "attachments" DROP CONSTRAINT "FK_attachments_ticket_id"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP CONSTRAINT "FK_comments_user_id"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP CONSTRAINT "FK_comments_ticket_id"`);
        await queryRunner.query(`ALTER TABLE "activity_logs" DROP CONSTRAINT "FK_activity_logs_user_id"`);
        await queryRunner.query(`ALTER TABLE "activity_logs" DROP CONSTRAINT "FK_activity_logs_ticket_id"`);
        await queryRunner.query(`ALTER TABLE "statuses" DROP CONSTRAINT "FK_statuses_project_id"`);
        await queryRunner.query(`ALTER TABLE "labels" DROP CONSTRAINT "FK_labels_project_id"`);
        await queryRunner.query(`ALTER TABLE "ticket_labels" DROP CONSTRAINT "FK_ticket_labels_label_id"`);
        await queryRunner.query(`ALTER TABLE "ticket_labels" DROP CONSTRAINT "FK_ticket_labels_ticket_id"`);
        await queryRunner.query(`ALTER TABLE "ticket_assignees" DROP CONSTRAINT "FK_ticket_assignees_user_id"`);
        await queryRunner.query(`ALTER TABLE "ticket_assignees" DROP CONSTRAINT "FK_ticket_assignees_ticket_id"`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP CONSTRAINT "FK_tickets_parent_ticket_id"`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP CONSTRAINT "FK_tickets_status_id"`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP CONSTRAINT "FK_tickets_created_by"`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP CONSTRAINT "FK_tickets_sprint_id"`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP CONSTRAINT "FK_tickets_project_id"`);
        await queryRunner.query(`ALTER TABLE "sprints" DROP CONSTRAINT "FK_sprints_project_id"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "FK_projects_workspace_id"`);
        await queryRunner.query(`ALTER TABLE "workspaces" DROP CONSTRAINT "FK_workspaces_owner_id"`);
        await queryRunner.query(`DROP INDEX "public"."uq_workspace_members_workspace_user"`);
        await queryRunner.query(`DROP INDEX "public"."idx_attachment_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_tickets_status_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_tickets_parent_ticket_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_tickets_project_status"`);
        await queryRunner.query(`DROP INDEX "public"."unique_project_name_per_workspace"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ticket_assignees_ticket_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ticket_assignees_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ticket_labels_ticket_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ticket_labels_label_id"`);
        await queryRunner.query(`ALTER TABLE "attachments" DROP CONSTRAINT "CHK_attachments_reference"`);
        await queryRunner.query(`ALTER TABLE "processed_events" ADD "retryCount" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "processed_events" ADD "lastError" text`);
        await queryRunner.query(`ALTER TABLE "processed_events" ADD "isProcessed" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "processed_events" ADD "lastAttemptAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TYPE "public"."workspace_role_enum" RENAME TO "workspace_role_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."workspace_members_role_enum" AS ENUM('ADMIN', 'MEMBER')`);
        await queryRunner.query(`ALTER TABLE "workspace_members" ALTER COLUMN "role" TYPE "public"."workspace_members_role_enum" USING "role"::"text"::"public"."workspace_members_role_enum"`);
        await queryRunner.query(`DROP TYPE "public"."workspace_role_enum_old"`);
        await queryRunner.query(`ALTER TABLE "comments" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TYPE "public"."activity_action_enum" RENAME TO "activity_action_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."activity_logs_action_enum" AS ENUM('TICKET_CREATED', 'TITLE_UPDATED', 'DESCRIPTION_UPDATED', 'STATUS_CHANGED', 'PRIORITY_CHANGED', 'ASSIGNEE_CHANGED', 'MOVED_TO_SPRINT', 'REMOVED_FROM_SPRINT', 'SPRINT_ASSIGNMENT_CHANGED', 'MOVED_TO_BACKLOG', 'SPRINT_CHANGED', 'TICKET_REORDERED', 'DUE_DATE_CHANGED', 'ATTACHMENT_ADDED')`);
        await queryRunner.query(`ALTER TABLE "activity_logs" ALTER COLUMN "action" TYPE "public"."activity_logs_action_enum" USING "action"::"text"::"public"."activity_logs_action_enum"`);
        await queryRunner.query(`DROP TYPE "public"."activity_action_enum_old"`);
        await queryRunner.query(`ALTER TABLE "activity_logs" ALTER COLUMN "metadata" DROP NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."status_category_enum" RENAME TO "status_category_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."statuses_category_enum" AS ENUM('TODO', 'IN_PROGRESS', 'DONE')`);
        await queryRunner.query(`ALTER TABLE "statuses" ALTER COLUMN "category" TYPE "public"."statuses_category_enum" USING "category"::"text"::"public"."statuses_category_enum"`);
        await queryRunner.query(`DROP TYPE "public"."status_category_enum_old"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ticket_project_status_priority"`);
        await queryRunner.query(`ALTER TYPE "public"."ticket_priority_enum" RENAME TO "ticket_priority_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."tickets_priority_enum" AS ENUM('LOW', 'MEDIUM', 'HIGH')`);
        await queryRunner.query(`ALTER TABLE "tickets" ALTER COLUMN "priority" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "tickets" ALTER COLUMN "priority" TYPE "public"."tickets_priority_enum" USING "priority"::"text"::"public"."tickets_priority_enum"`);
        await queryRunner.query(`DROP TYPE "public"."ticket_priority_enum_old"`);
        await queryRunner.query(`ALTER TABLE "sprints" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "sprints" ADD "name" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."sprint_status_enum" RENAME TO "sprint_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."sprints_status_enum" AS ENUM('PLANNED', 'ACTIVE', 'COMPLETED')`);
        await queryRunner.query(`ALTER TABLE "sprints" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "sprints" ALTER COLUMN "status" TYPE "public"."sprints_status_enum" USING "status"::"text"::"public"."sprints_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."sprint_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "name" character varying(200) NOT NULL`);
        await queryRunner.query(`DROP INDEX "public"."uq_project_key"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "key"`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "key" character varying(20) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "workspaces" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "workspaces" ADD "name" character varying(200) NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."user_theme_enum" RENAME TO "user_theme_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."users_theme_enum" AS ENUM('DARK', 'LIGHT')`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "theme" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "theme" TYPE "public"."users_theme_enum" USING "theme"::"text"::"public"."users_theme_enum"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "theme" SET DEFAULT 'DARK'`);
        await queryRunner.query(`DROP TYPE "public"."user_theme_enum_old"`);
        await queryRunner.query(`ALTER TABLE "processed_events" ALTER COLUMN "processedAt" SET DEFAULT now()`);
        await queryRunner.query(`CREATE INDEX "idx_comment_created_at" ON "comments" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_activity_log_created_at" ON "activity_logs" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_ticket_labels_label_id" ON "ticket_labels" ("label_id") `);
        await queryRunner.query(`CREATE INDEX "idx_ticket_labels_ticket_id" ON "ticket_labels" ("ticket_id") `);
        await queryRunner.query(`CREATE INDEX "idx_ticket_assignees_user_id" ON "ticket_assignees" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_ticket_assignees_ticket_id" ON "ticket_assignees" ("ticket_id") `);
        await queryRunner.query(`CREATE INDEX "idx_ticket_project_status_priority" ON "tickets" ("project_id", "status_id", "priority") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_project_key" ON "projects" ("key") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_806c4aad6c2fd413cb2ba5eb81" ON "workspaces" ("owner_id", "name") `);
        await queryRunner.query(`CREATE INDEX "IDX_b36b35959597de6ae8bf2b43ca" ON "ticket_assignees" ("ticket_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_c653a891aa11e08c1382b1f80f" ON "ticket_assignees" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_a4c890bc61e8cc92ce429e878c" ON "ticket_labels" ("ticket_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ecf91c0c8152320a9bbcaffdca" ON "ticket_labels" ("label_id") `);
        await queryRunner.query(`ALTER TABLE "workspace_members" ADD CONSTRAINT "uq_workspace_member_workspace_user" UNIQUE ("workspace_id", "user_id")`);
        await queryRunner.query(`ALTER TABLE "workspace_members" ADD CONSTRAINT "FK_4a7c584ddfe855379598b5e20fd" FOREIGN KEY ("workspace_id") REFERENCES "workspaces"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workspace_members" ADD CONSTRAINT "FK_4e83431119fa585fc7aa8b817db" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attachments" ADD CONSTRAINT "FK_73d871f247ffebda5dc3f0df8a4" FOREIGN KEY ("ticket_id") REFERENCES "tickets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attachments" ADD CONSTRAINT "FK_b4b436948b623e8e765bd1c0977" FOREIGN KEY ("comment_id") REFERENCES "comments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attachments" ADD CONSTRAINT "FK_e25812e3fd9b3f3edf11b2c5d58" FOREIGN KEY ("uploaded_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comments" ADD CONSTRAINT "FK_be8180d9b44a05e449b85f5b773" FOREIGN KEY ("ticket_id") REFERENCES "tickets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comments" ADD CONSTRAINT "FK_4c675567d2a58f0b07cef09c13d" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activity_logs" ADD CONSTRAINT "FK_24a25bc088a5fe8677eb0f1b985" FOREIGN KEY ("ticket_id") REFERENCES "tickets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activity_logs" ADD CONSTRAINT "FK_d54f841fa5478e4734590d44036" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "statuses" ADD CONSTRAINT "FK_081c9cefe5fb6b856ed183bbeb8" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "labels" ADD CONSTRAINT "FK_68b0da461f6765824f6db642f12" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ticket_labels" ADD CONSTRAINT "FK_a4c890bc61e8cc92ce429e878ca" FOREIGN KEY ("ticket_id") REFERENCES "tickets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ticket_labels" ADD CONSTRAINT "FK_ecf91c0c8152320a9bbcaffdca5" FOREIGN KEY ("label_id") REFERENCES "labels"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ticket_assignees" ADD CONSTRAINT "FK_b36b35959597de6ae8bf2b43ca6" FOREIGN KEY ("ticket_id") REFERENCES "tickets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ticket_assignees" ADD CONSTRAINT "FK_c653a891aa11e08c1382b1f80f3" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD CONSTRAINT "FK_ad2a415688c613c9897f7975efd" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD CONSTRAINT "FK_82ea28a5e1dfc8bf74ae8c8e091" FOREIGN KEY ("sprint_id") REFERENCES "sprints"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD CONSTRAINT "FK_857f281a741501bc1e4c67c574f" FOREIGN KEY ("status_id") REFERENCES "statuses"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD CONSTRAINT "FK_8798a589dc4c71b6d0e8c2b9fc3" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD CONSTRAINT "FK_de16e1bb03cdb5cb756631b2592" FOREIGN KEY ("parent_ticket_id") REFERENCES "tickets"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprints" ADD CONSTRAINT "FK_82145010051f3f2fc94671c0b35" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "FK_af78b8fc6857fe0a10d1bb1699e" FOREIGN KEY ("workspace_id") REFERENCES "workspaces"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workspaces" ADD CONSTRAINT "FK_3bc45ecdd8fdc2108bb92516dde" FOREIGN KEY ("owner_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "workspaces" DROP CONSTRAINT "FK_3bc45ecdd8fdc2108bb92516dde"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "FK_af78b8fc6857fe0a10d1bb1699e"`);
        await queryRunner.query(`ALTER TABLE "sprints" DROP CONSTRAINT "FK_82145010051f3f2fc94671c0b35"`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP CONSTRAINT "FK_de16e1bb03cdb5cb756631b2592"`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP CONSTRAINT "FK_8798a589dc4c71b6d0e8c2b9fc3"`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP CONSTRAINT "FK_857f281a741501bc1e4c67c574f"`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP CONSTRAINT "FK_82ea28a5e1dfc8bf74ae8c8e091"`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP CONSTRAINT "FK_ad2a415688c613c9897f7975efd"`);
        await queryRunner.query(`ALTER TABLE "ticket_assignees" DROP CONSTRAINT "FK_c653a891aa11e08c1382b1f80f3"`);
        await queryRunner.query(`ALTER TABLE "ticket_assignees" DROP CONSTRAINT "FK_b36b35959597de6ae8bf2b43ca6"`);
        await queryRunner.query(`ALTER TABLE "ticket_labels" DROP CONSTRAINT "FK_ecf91c0c8152320a9bbcaffdca5"`);
        await queryRunner.query(`ALTER TABLE "ticket_labels" DROP CONSTRAINT "FK_a4c890bc61e8cc92ce429e878ca"`);
        await queryRunner.query(`ALTER TABLE "labels" DROP CONSTRAINT "FK_68b0da461f6765824f6db642f12"`);
        await queryRunner.query(`ALTER TABLE "statuses" DROP CONSTRAINT "FK_081c9cefe5fb6b856ed183bbeb8"`);
        await queryRunner.query(`ALTER TABLE "activity_logs" DROP CONSTRAINT "FK_d54f841fa5478e4734590d44036"`);
        await queryRunner.query(`ALTER TABLE "activity_logs" DROP CONSTRAINT "FK_24a25bc088a5fe8677eb0f1b985"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP CONSTRAINT "FK_4c675567d2a58f0b07cef09c13d"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP CONSTRAINT "FK_be8180d9b44a05e449b85f5b773"`);
        await queryRunner.query(`ALTER TABLE "attachments" DROP CONSTRAINT "FK_e25812e3fd9b3f3edf11b2c5d58"`);
        await queryRunner.query(`ALTER TABLE "attachments" DROP CONSTRAINT "FK_b4b436948b623e8e765bd1c0977"`);
        await queryRunner.query(`ALTER TABLE "attachments" DROP CONSTRAINT "FK_73d871f247ffebda5dc3f0df8a4"`);
        await queryRunner.query(`ALTER TABLE "workspace_members" DROP CONSTRAINT "FK_4e83431119fa585fc7aa8b817db"`);
        await queryRunner.query(`ALTER TABLE "workspace_members" DROP CONSTRAINT "FK_4a7c584ddfe855379598b5e20fd"`);
        await queryRunner.query(`ALTER TABLE "workspace_members" DROP CONSTRAINT "uq_workspace_member_workspace_user"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ecf91c0c8152320a9bbcaffdca"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a4c890bc61e8cc92ce429e878c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c653a891aa11e08c1382b1f80f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b36b35959597de6ae8bf2b43ca"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_806c4aad6c2fd413cb2ba5eb81"`);
        await queryRunner.query(`DROP INDEX "public"."uq_project_key"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ticket_project_status_priority"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ticket_assignees_ticket_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ticket_assignees_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ticket_labels_ticket_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ticket_labels_label_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_activity_log_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_comment_created_at"`);
        await queryRunner.query(`ALTER TABLE "processed_events" ALTER COLUMN "processedAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`CREATE TYPE "public"."user_theme_enum_old" AS ENUM('DARK', 'LIGHT')`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "theme" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "theme" TYPE "public"."user_theme_enum_old" USING "theme"::"text"::"public"."user_theme_enum_old"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "theme" SET DEFAULT 'DARK'`);
        await queryRunner.query(`DROP TYPE "public"."users_theme_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."user_theme_enum_old" RENAME TO "user_theme_enum"`);
        await queryRunner.query(`ALTER TABLE "workspaces" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "workspaces" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "key"`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "key" character varying NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_project_key" ON "projects" ("key") `);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."sprint_status_enum_old" AS ENUM('PLANNED', 'ACTIVE', 'COMPLETED')`);
        await queryRunner.query(`ALTER TABLE "sprints" ALTER COLUMN "status" TYPE "public"."sprint_status_enum_old" USING "status"::"text"::"public"."sprint_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "sprints" ALTER COLUMN "status" SET DEFAULT 'PLANNED'`);
        await queryRunner.query(`DROP TYPE "public"."sprints_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."sprint_status_enum_old" RENAME TO "sprint_status_enum"`);
        await queryRunner.query(`ALTER TABLE "sprints" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "sprints" ADD "name" character varying`);
        await queryRunner.query(`CREATE TYPE "public"."ticket_priority_enum_old" AS ENUM('LOW', 'MEDIUM', 'HIGH')`);
        await queryRunner.query(`ALTER TABLE "tickets" ALTER COLUMN "priority" TYPE "public"."ticket_priority_enum_old" USING "priority"::"text"::"public"."ticket_priority_enum_old"`);
        await queryRunner.query(`ALTER TABLE "tickets" ALTER COLUMN "priority" SET DEFAULT 'MEDIUM'`);
        await queryRunner.query(`DROP TYPE "public"."tickets_priority_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."ticket_priority_enum_old" RENAME TO "ticket_priority_enum"`);
        await queryRunner.query(`CREATE INDEX "idx_ticket_project_status_priority" ON "tickets" ("priority", "project_id", "status_id") `);
        await queryRunner.query(`CREATE TYPE "public"."status_category_enum_old" AS ENUM('TODO', 'IN_PROGRESS', 'DONE')`);
        await queryRunner.query(`ALTER TABLE "statuses" ALTER COLUMN "category" TYPE "public"."status_category_enum_old" USING "category"::"text"::"public"."status_category_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."statuses_category_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."status_category_enum_old" RENAME TO "status_category_enum"`);
        await queryRunner.query(`ALTER TABLE "activity_logs" ALTER COLUMN "metadata" SET NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."activity_action_enum_old" AS ENUM('TICKET_CREATED', 'TITLE_UPDATED', 'DESCRIPTION_UPDATED', 'STATUS_CHANGED', 'PRIORITY_CHANGED', 'ASSIGNEE_CHANGED', 'MOVED_TO_SPRINT', 'MOVED_TO_BACKLOG', 'SPRINT_CHANGED', 'TICKET_REORDERED', 'DUE_DATE_CHANGED', 'REMOVED_FROM_SPRINT')`);
        await queryRunner.query(`ALTER TABLE "activity_logs" ALTER COLUMN "action" TYPE "public"."activity_action_enum_old" USING "action"::"text"::"public"."activity_action_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."activity_logs_action_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."activity_action_enum_old" RENAME TO "activity_action_enum"`);
        await queryRunner.query(`ALTER TABLE "comments" ALTER COLUMN "updated_at" DROP DEFAULT`);
        await queryRunner.query(`CREATE TYPE "public"."workspace_role_enum_old" AS ENUM('ADMIN', 'MEMBER')`);
        await queryRunner.query(`ALTER TABLE "workspace_members" ALTER COLUMN "role" TYPE "public"."workspace_role_enum_old" USING "role"::"text"::"public"."workspace_role_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."workspace_members_role_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."workspace_role_enum_old" RENAME TO "workspace_role_enum"`);
        await queryRunner.query(`ALTER TABLE "processed_events" DROP COLUMN "lastAttemptAt"`);
        await queryRunner.query(`ALTER TABLE "processed_events" DROP COLUMN "isProcessed"`);
        await queryRunner.query(`ALTER TABLE "processed_events" DROP COLUMN "lastError"`);
        await queryRunner.query(`ALTER TABLE "processed_events" DROP COLUMN "retryCount"`);
        await queryRunner.query(`ALTER TABLE "attachments" ADD CONSTRAINT "CHK_attachments_reference" CHECK ((((ticket_id IS NOT NULL) AND (comment_id IS NULL)) OR ((ticket_id IS NULL) AND (comment_id IS NOT NULL))))`);
        await queryRunner.query(`CREATE INDEX "idx_ticket_labels_label_id" ON "ticket_labels" ("label_id") `);
        await queryRunner.query(`CREATE INDEX "idx_ticket_labels_ticket_id" ON "ticket_labels" ("ticket_id") `);
        await queryRunner.query(`CREATE INDEX "idx_ticket_assignees_user_id" ON "ticket_assignees" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_ticket_assignees_ticket_id" ON "ticket_assignees" ("ticket_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "unique_project_name_per_workspace" ON "projects" ("workspace_id") `);
        await queryRunner.query(`CREATE INDEX "idx_tickets_project_status" ON "tickets" ("project_id", "status_id") `);
        await queryRunner.query(`CREATE INDEX "idx_tickets_parent_ticket_id" ON "tickets" ("parent_ticket_id") `);
        await queryRunner.query(`CREATE INDEX "idx_tickets_status_id" ON "tickets" ("status_id") `);
        await queryRunner.query(`CREATE INDEX "idx_attachment_created_at" ON "attachments" ("created_at") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_workspace_members_workspace_user" ON "workspace_members" ("user_id", "workspace_id") `);
        await queryRunner.query(`ALTER TABLE "workspaces" ADD CONSTRAINT "FK_workspaces_owner_id" FOREIGN KEY ("owner_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "FK_projects_workspace_id" FOREIGN KEY ("workspace_id") REFERENCES "workspaces"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprints" ADD CONSTRAINT "FK_sprints_project_id" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD CONSTRAINT "FK_tickets_project_id" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD CONSTRAINT "FK_tickets_sprint_id" FOREIGN KEY ("sprint_id") REFERENCES "sprints"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD CONSTRAINT "FK_tickets_created_by" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD CONSTRAINT "FK_tickets_status_id" FOREIGN KEY ("status_id") REFERENCES "statuses"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD CONSTRAINT "FK_tickets_parent_ticket_id" FOREIGN KEY ("parent_ticket_id") REFERENCES "tickets"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ticket_assignees" ADD CONSTRAINT "FK_ticket_assignees_ticket_id" FOREIGN KEY ("ticket_id") REFERENCES "tickets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ticket_assignees" ADD CONSTRAINT "FK_ticket_assignees_user_id" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ticket_labels" ADD CONSTRAINT "FK_ticket_labels_ticket_id" FOREIGN KEY ("ticket_id") REFERENCES "tickets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ticket_labels" ADD CONSTRAINT "FK_ticket_labels_label_id" FOREIGN KEY ("label_id") REFERENCES "labels"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "labels" ADD CONSTRAINT "FK_labels_project_id" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "statuses" ADD CONSTRAINT "FK_statuses_project_id" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activity_logs" ADD CONSTRAINT "FK_activity_logs_ticket_id" FOREIGN KEY ("ticket_id") REFERENCES "tickets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activity_logs" ADD CONSTRAINT "FK_activity_logs_user_id" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comments" ADD CONSTRAINT "FK_comments_ticket_id" FOREIGN KEY ("ticket_id") REFERENCES "tickets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comments" ADD CONSTRAINT "FK_comments_user_id" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attachments" ADD CONSTRAINT "FK_attachments_ticket_id" FOREIGN KEY ("ticket_id") REFERENCES "tickets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attachments" ADD CONSTRAINT "FK_attachments_comment_id" FOREIGN KEY ("comment_id") REFERENCES "comments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attachments" ADD CONSTRAINT "FK_attachments_uploaded_by" FOREIGN KEY ("uploaded_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workspace_members" ADD CONSTRAINT "FK_workspace_members_workspace_id" FOREIGN KEY ("workspace_id") REFERENCES "workspaces"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workspace_members" ADD CONSTRAINT "FK_workspace_members_user_id" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
    }

}
